version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/edu:/var/www/edu
  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src/edu:/var/www/edu
  mongodb:
    image: mongo:6-jammy
  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src/edu:/var/www/edu
    depends_on:
      - php
      - mongodb
  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src/edu:/var/www/edu
    command: php artisan migrate
    depends_on:
      - php
      - mongodb
