version: "3.8"

services:
  nginx:
    build:
      context: src/edu
      dockerfile: nginx.Dockerfile
    ports:
      - "127.0.0.1:8000:80"
  php:
    build:
      context: src/edu
      dockerfile: php.Dockerfile
    depends_on:
      - nginx
  mongodb:
    image: mongo:6-jammy
    volumes:
      - ./mongo_data:/data/db
    depends_on:
      - nginx
  composer:
    build:
      context: src/edu
      dockerfile: composer.Dockerfile
    depends_on:
      - php
      - mongodb
  artisan:
    build:
      context: src/edu
      dockerfile: php.Dockerfile
    command: php artisan migrate
    depends_on:
      - php
      - mongodb
      - composer
